# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Articles_MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Articles_MVVM
pod 'SDWebImage', '~> 5.5.2'
end
